version: "3.9"
   
services:
  api:
    build: .
    image: juancamiloceron/django
    container_name: django_api
    environment:
      - APP_MODE=api
    env_file:
      - .env
    volumes:
      - .:/code
      - /static:/static
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: django_reverse_proxy
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /static:/static
    depends_on:
      - api

  worker:
    image: juancamiloceron/django
    container_name: django_celery_worker
    environment:
      - APP_MODE=worker
    env_file:
      - .env 
    volumes:
      - .:/code
    depends_on:
      - api
  
  scheduler:
    image: juancamiloceron/django
    container_name: django_celery_scheduler
    environment:
      - APP_MODE=scheduler
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - api