apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-statics
spec:
  resources:
    requests:
      storage: 20M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
