apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      volumes:
      - name: django-statics
        persistentVolumeClaim:
          claimName: django-statics

      containers:
        - image: jc2acr.azurecr.io/django:white
          imagePullPolicy: Never
          name: django-api
          # command: ["/bin/bash", "-c"]
          # args: ["python manage.py migrate && uwsgi --http 0.0.0.0:8000 --processes 1 --module django_web.wsgi:application"]
          env:
          - name: APP_MODE
            value: "api"
          envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-config
          ports:
            - containerPort: 8000
              name: django-api
          resources:
            limits:
              memory: "256M"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /static
              name: django-statics