apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-worker
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: juancamiloceron/django:v1
          imagePullPolicy: Never
          name: django-worker
          env:
          - name: APP_MODE
            value: "worker"
          envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-config