apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-cdn
  labels:
    app: django-cdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-cdn
  template:
    metadata:
      labels:
        app: django-cdn
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: django-statics
        persistentVolumeClaim:
          claimName: django-storage-claim

      containers:
        - image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: django-cdn
          ports:
            - containerPort: 8000
              name: django-cdn
          resources:
            limits:
              memory: "256M"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
              readOnly: true
            - mountPath: /static
              name: django-statics
            