apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
        - image: juancamiloceron/django:v1
          imagePullPolicy: Never
          name: django-api
          env:
          - name: APP_MODE
            value: "api"
          envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-config
          ports:
            - containerPort: 8000
              name: django-gunicorn
          resources:
            limits:
              memory: "256M"
              cpu: "1000m"