apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-scheduler
  labels:
    app: django-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-scheduler
  template:
    metadata:
      labels:
        app: django-scheduler
    spec:
      containers:
        - image: juancamiloceron/django:v1
          imagePullPolicy: Never
          name: django-scheduler
          env:
          - name: APP_MODE
            value: "scheduler"
          envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-config
          resources:
            limits:
              memory: "256M"
              cpu: "1000m"