apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-worker
  labels:
    app: django-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-worker
  template:
    metadata:
      labels:
        app: django-worker
    spec:
      containers:
        - image: jc2acr.azurecr.io/django:v1.2
          name: django-worker
          env:
          - name: APP_MODE
            value: "worker"
          envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-config
          resources:
            limits:
              memory: "256M"
              cpu: "500m"