apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      volumes:
      - name: django-statics
        persistentVolumeClaim:
          claimName: django-storage-claim

      containers:
        - image: jc2acr.azurecr.io/django:uwsgi5
          name: django-api
          env:
          - name: APP_MODE
            value: "api"
          envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-config
          ports:
            - containerPort: 8000
              name: django-api
          resources:
            limits:
              memory: "256M"
              cpu: "500m"
          volumeMounts:
            - mountPath: /static
              name: django-statics